### PR TITLE
Show notes for skipped tests if they exist and add support for expectedFailure test results

### PR DESCRIPTION
**Pull request by coolreader18**

### CODE REVIEW

**Comment by coolreader18** [comment]
@mireille-raad could you review this?

**Comment by coolreader18** [comment]
I shifted skips to the failure spot in the summary because there is never a failure that gets to the data; if any of the tests fail then they shouldn't be on master and they results data won't get pushed to the repository. Anyway, here's what the summary graph looks like now:
image

**Comment by mireille-raad** [comment]
this looks good to me. I was expecting the mobile layout to break, but even that still looks good.

Thanks for adding the expected failures and other comments.

**Comment by mireille-raad** [comment]
Maybe we can do one thing:

remove the "empty" from the filters? before this filtered the empty rows, now these rows have "expected failures".

or 

rename "empty" to "summary view" and pull it to the right. this can look like this
Screen Shot 2020-05-29 at 10 23 15 AM

You only need to rename "empty" -> "summary view" and add a class/css with:
`
margin-left: auto;
`

**Pull request merged**
