### PR TITLE
display regrtests_results.json in dashboard/html page

### PR DESCRIPTION
**Pull request by mireille-raad**
This is a dashboard-y page that displays the regression test results from `_data/regrtests_results.json`

**Markdown file** 
`pages/regression-tests-results.markdown` 

**url**. 
base url +  /pages/regression-tests-results.html
You can change the url of the dashboard by changing the name of that file. Same for title etc..

**The page has**
- simple listing + grouping by module.
- emojis make it easier on the eyes to spot the status without actually having to read. It is more elegant than just coloring things with red or green... or at least more fun.
- basic filter functionality.

The layout is responsive, I tried to make the layout work as much as possible on mobile. It is decent on mobile devices, but could be better. The names of modules is long, so it takes up space on mobile devices.

**Fields**
I added the fields that seemed to be most frequently filled. A lot of the fields were not, so I didn't add those. Tell me if something else needs to be there.

**Question**
Should we add a way to navigate to different modules? does this need to be more usable?

### CODE REVIEW

**Comment by mireille-raad** [comment]
screenshots 

Screen Shot 2020-05-15 at 8 38 04 PM

another section 

Screen Shot 2020-05-15 at 8 38 30 PM

and another 

Screen Shot 2020-05-15 at 8 38 14 PM

**Comment by mireille-raad** [comment]
> Sorry this took a while to get to; this looks really great! Thanks for working on this!

sure. thanks for creating the data file and automating it.

**Comment by youknowone** [comment]
I like this page a lot, thank you!

**Comment by mireille-raad** [comment]
@youknowone 😁I am glad.

**Pull request merged**
